### ISSUE TITLE
大佬能不能解除三个添加设备的限制

### ISSUE THREAD

**Issue by hallerool** [HeHang0/AudioShare#1]
大佬这个软件非常好用能不能解除三个添加设备的限制😊改成五个设备或者不限制设备添加。

**Comment by HeHang0** [comment]
没有设备数量的限制，ui显示三个，有滚动条可以滚动全部展示的

**Comment by HeHang0** [comment]
> 大佬这个软件非常好用能不能解除三个添加设备的限制😊改成五个设备或者不限制设备添加。


没有设备数量的限制，ui显示三个，有滚动条可以滚动全部展示的
