### ISSUE TITLE
可能是一个稳定性问题

### ISSUE THREAD

**Issue by aeneask** [HeHang0/AudioShare#2]
感谢开发这么好的东东。
该问题具体场景：电脑播放一个本地视频，R1发声正常。电脑锁屏后（没有休眠）自动暂停播放，过了个把小时（也可能30分钟，但电脑没有休眠）后，重新登录电脑，继续播放视频会没有声音，需要在AudioShare里断开再连接后，R1才会继续发声。期间R1本身没有什么操作。

**Comment by aeneask** [comment]
复现很容易：基本上系统锁屏，再登录就会出现这个问题。

**Comment by HeHang0** [comment]
> 复现很容易：基本上系统锁屏，过一段时间，再登录就会出现这个问题。操作系统是win10

wifi连接还是adb连接呀，这个问题我之前有，加了心跳检测之后好了，大概率是网络假死，程序以为连接正常

**Comment by aeneask** [comment]
> > 复现很容易：基本上系统锁屏，过一段时间，再登录就会出现这个问题。操作系统是win10
> 
> wifi连接还是adb连接呀，这个问题我之前有，加了心跳检测之后好了，大概率是网络假死，程序以为连接正常

wifi连接，已使用最新的版本，上周末还是有这个问题，需要断开、刷新、连接后才行

**Comment by HeHang0** [comment]
> > > 复现很容易：基本上系统锁屏，过一段时间，再登录就会出现这个问题。操作系统是win10
> > 
> > 
> > wifi连接还是adb连接呀，这个问题我之前有，加了心跳检测之后好了，大概率是网络假死，程序以为连接正常
> 
> wifi连接，已使用最新的1.7.6版本，上周末还是有这个问题，需要断开、刷新、连接后才行

可以尝试最新1.7.7版本，加入了重连机制

**Comment by aeneask** [comment]
> > > > 复现很容易：基本上系统锁屏，过一段时间，再登录就会出现这个问题。操作系统是win10
> > > 
> > > 
> > > wifi连接还是adb连接呀，这个问题我之前有，加了心跳检测之后好了，大概率是网络假死，程序以为连接正常
> > 
> > 
> > wifi连接，已使用最新的1.7.6版本，上周末还是有这个问题，需要断开、刷新、连接后才行
> 
> 可以尝试最新1.7.8版本，加入了重连机制

试了最新的1.7.8，还是有此问题。而且在断开后，刷新后，点连接，怎么也连不上了。。。

**Comment by HeHang0** [comment]
> > > > > 复现很容易：基本上系统锁屏，过一段时间，再登录就会出现这个问题。操作系统是win10
> > > > 
> > > > 
> > > > wifi连接还是adb连接呀，这个问题我之前有，加了心跳检测之后好了，大概率是网络假死，程序以为连接正常
> > > 
> > > 
> > > wifi连接，已使用最新的1.7.6版本，上周末还是有这个问题，需要断开、刷新、连接后才行
> > 
> > 
> > 可以尝试最新1.7.8版本，加入了重连机制
> 
> 试了最新的1.7.8，还是有此问题。而且在断开后，刷新后，点连接，怎么也连不上了。。。退回1.7.6后，可以重连上了
> 
> 周末使用更新，重试了1.7.8，能重连上，但问题依旧：锁屏一段时间后还是没有声音，需要断开重连才行

已经复现问题，静待解决

**Comment by komazhou** [comment]
> > > > > > 复现很容易：基本上系统锁屏，过一段时间，再登录就会出现这个问题。操作系统是win10
> > > > > 
> > > > > 
> > > > > wifi连接还是adb连接呀，这个问题我之前有，加了心跳检测之后好了，大概率是网络假死，程序以为连接正常
> > > > 
> > > > 
> > > > wifi连接，已使用最新的1.7.6版本，上周末还是有这个问题，需要断开、刷新、连接后才行
> > > 
> > > 
> > > 可以尝试最新1.7.8版本，加入了重连机制
> > 
> > 
> > 试了最新的1.7.8，还是有此问题。而且在断开后，刷新后，点连接，怎么也连不上了。。。退回1.7.6后，可以重连上了
> > 周末使用更新，重试了1.7.8，能重连上，但问题依旧：锁屏一段时间后还是没有声音，需要断开重连才行
> 
> 已经复现问题，静待解决

同样1.7.8版本，需要退出之后，重新打开一次程序才能连接发声
既然需要退出程序之后再次开启就能自动连接并正常发声，不知道能否通过增加一个重启的功能来解决，在托盘图标上右键重启，

**Comment by komazhou** [comment]
目前自己用一段ahk代码来实现重启，暂时解决问题

    Run, taskkill /f /t /im AudioShare.exe
	Sleep, 500
    Run, %COMMANDER_PATH%\Tools\AudioShare\AudioShare.exe

**Comment by HeHang0** [comment]
我本地复现是网络连接正常，但是音响音量不知道什么原因自动为0了，可以使用[最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)看看

**Comment by aeneask** [comment]
> 我本地复现是网络连接正常，但是音响音量不知道什么原因自动为0了，可以使用[最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)看看

试了1.7.9版本，还是不行啊，问题依旧。而且通过R1的顶部触控尝试增大音量，也没用

**Comment by HeHang0** [comment]
> > 我本地复现是网络连接正常，但是音响音量不知道什么原因自动为0了，可以使用[最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)看看
> 
> 试了1.7.9版本，还是不行啊，问题依旧。而且通过R1的顶部触控尝试增大音量，也没用

可以贴一下不可用之后的logcat看看

**Comment by aeneask** [comment]
> > > 我本地复现是网络连接正常，但是音响音量不知道什么原因自动为0了，可以使用[最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)看看
> > 
> > 
> > 试了1.7.9版本，还是不行啊，问题依旧。而且通过R1的顶部触控尝试增大音量，也没用
> 
> 可以贴一下不可用之后的logcat看看

用adb logcat输出了一下
[logcat.log](https://github.com/HeHang0/AudioShare/files/15262069/logcat.log)

**Comment by HeHang0** [comment]
> > > > 我本地复现是网络连接正常，但是音响音量不知道什么原因自动为0了，可以使用[最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)看看
> > > 
> > > 
> > > 试了1.7.9版本，还是不行啊，问题依旧。而且通过R1的顶部触控尝试增大音量，也没用
> > 
> > 
> > 可以贴一下不可用之后的logcat看看
> 
> 用adb logcat输出了一下 [logcat.log](https://github.com/HeHang0/AudioShare/files/15262069/logcat.log)

看上去apk里面是正常的，电脑没产生音频数据过来，是不是你电脑上音频输出会自动切换到其他声卡，或者是不是你选的显示器附带的输出，锁屏后这个设备休眠了，没有自动切换回来

**Comment by aeneask** [comment]
> > > > > 我本地复现是网络连接正常，但是音响音量不知道什么原因自动为0了，可以使用[最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)看看
> > > > 
> > > > 
> > > > 试了1.7.9版本，还是不行啊，问题依旧。而且通过R1的顶部触控尝试增大音量，也没用
> > > 
> > > 
> > > 可以贴一下不可用之后的logcat看看
> > 
> > 
> > 用adb logcat输出了一下 [logcat.log](https://github.com/HeHang0/AudioShare/files/15262069/logcat.log)
> 
> 看上去apk里面是正常的，电脑没产生音频数据过来，是不是你电脑上音频输出会自动切换到其他声卡，或者是不是你选的显示器附带的输出，锁屏后这个设备休眠了，没有自动切换回来

可能确实是用了显示器附带的输出，等下班回家后我再确认下

**Comment by aeneask** [comment]
> > > > > 我本地复现是网络连接正常，但是音响音量不知道什么原因自动为0了，可以使用[最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)看看
> > > > 
> > > > 
> > > > 试了1.7.9版本，还是不行啊，问题依旧。而且通过R1的顶部触控尝试增大音量，也没用
> > > 
> > > 
> > > 可以贴一下不可用之后的logcat看看
> > 
> > 
> > 用adb logcat输出了一下 [logcat.log](https://github.com/HeHang0/AudioShare/files/15262069/logcat.log)
> 
> 看上去apk里面是正常的，电脑没产生音频数据过来，是不是你电脑上音频输出会自动切换到其他声卡，或者是不是你选的显示器附带的输出，锁屏后这个设备休眠了，没有自动切换回来

确实是用了显示器附带的输出，因为itx主板要么插耳机口输出，要么只能选择显示器带的输出。锁屏后过一会屏幕超时会关闭，在系统中选择不自动关闭屏幕就好了。

感谢大佬，终于把这个问题帮我排查解决了。
