### ISSUE TITLE
如何卸载音箱端的AudioShare？

### ISSUE THREAD

**Issue by esverde** [HeHang0/AudioShare#3]

**Comment by aeneask** [comment]
用adb命令不行么？
以下是我从网上搜到的步骤：
在电脑上安装并配置 ADB。

1.连接 Android 设备到电脑并确保已开启 USB 调试。
（wifi模式、usb模式连接都可以。能安装audioshare，说明已经开启了usb调试模式了）

2.打开命令行窗口，输入 adb devices 并回车，确保设备已连接并识别。

3.输入 adb shell 并回车，进入 shell 模式。

4.输入 pm list packages 并回车，列出所有已安装的应用。

5.找到要卸载的应用的包名，输入 pm uninstall -k --user 0 包名 并回车卸载该应用。
注意：上面的步骤中的 "-k" 参数是可选的，用于保留应用的数据和缓存文件。

**Comment by HeHang0** [comment]
> _No description provided._

adb shell /system/bin/pm uninstall com.picapico.audioshare
