### ISSUE TITLE
安装AudioShare开机一段时间后会导致R1语音无法唤醒。

### ISSUE THREAD

**Issue by xdm2211** [HeHang0/AudioShare#5]
RT,R1音箱安装AudioShare1.7.8后，给予了root权限的【不给权限也一样】，音箱刚重启的时候语音唤醒什么的都正常，用蓝牙播放一段时间音频后，就无法响应任何语音回复了，喊他就没有任何反应，按键唤醒是正常的，多次尝试都是这样，重启后正常，但是卸载AudioShare后不管蓝牙播放运行多久语音唤醒都没有问题，盲猜会不会是AudioShare后台内存占用过多把斐讯的语音唤醒进程给干掉了？希望作者大大排查一下原因，同时发布的版本希望增加一个单纯连接电脑的新版本，不用在线播放音乐等网络功能的，以减小内存占用。。。。 再次感谢作者大大的付出！

**Comment by 99477204** [comment]
请教下怎么给root权限？

**Comment by xdm2211** [comment]
> 请教下怎么给root权限？

拆机刷入已经root的镜像。。我用的是一个养老固件，只带root，不会提示音箱未绑定的固件。

**Comment by 99477204** [comment]
> > 请教下怎么给root权限？
> 
> 拆机刷入已经root的镜像。。我用的是一个养老固件，只带root，不会提示音箱未绑定的固件。

root固件作者链接可以分享下吗

**Comment by xdm2211** [comment]
> > > 请教下怎么给root权限？
> > 
> > 
> > 拆机刷入已经root的镜像。。我用的是一个养老固件，只带root，不会提示音箱未绑定的固件。
> 
> root固件作者链接可以分享下吗

链接: https://pan.baidu.com/s/1G5x3B5LLVzApz7-8kGiSsg 提取码: rwta

**Comment by HeHang0** [comment]
[最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)加入了在线播放功能的关闭按钮，关闭后重启生效

**Comment by HeHang0** [comment]
> RT,R1音箱安装AudioShare1.7.8后，给予了root权限的【不给权限也一样】，音箱刚重启的时候语音唤醒什么的都正常，用蓝牙播放一段时间音频后，就无法响应任何语音回复了，喊他就没有任何反应，按键唤醒是正常的，多次尝试都是这样，重启后正常，但是卸载AudioShare后不管蓝牙播放运行多久语音唤醒都没有问题，盲猜会不会是AudioShare后台内存占用过多把斐讯的语音唤醒进程给干掉了？希望作者大大排查一下原因，同时发布的版本希望增加一个单纯连接电脑的新版本，不用在线播放音乐等网络功能的，以减小内存占用。。。。 再次感谢作者大大的付出！

可以贴一下正常的进程信息以及不能唤醒后的进程信息，我这边没有复现，可能是无关进程都被我关掉了

**Comment by xdm2211** [comment]
> > RT,R1音箱安装AudioShare1.7.8后，给予了root权限的【不给权限也一样】，音箱刚重启的时候语音唤醒什么的都正常，用蓝牙播放一段时间音频后，就无法响应任何语音回复了，喊他就没有任何反应，按键唤醒是正常的，多次尝试都是这样，重启后正常，但是卸载AudioShare后不管蓝牙播放运行多久语音唤醒都没有问题，盲猜会不会是AudioShare后台内存占用过多把斐讯的语音唤醒进程给干掉了？希望作者大大排查一下原因，同时发布的版本希望增加一个单纯连接电脑的新版本，不用在线播放音乐等网络功能的，以减小内存占用。。。。 再次感谢作者大大的付出！
> 
> 可以贴一下正常的进程信息以及不能唤醒后的进程信息，我这边没有复现，可能是无关进程都被我关掉了

这是语音无反应的后的进程，蓝牙正常连接播放状态。
C:\Users\admin>adb shell ps
USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME
root      1     0     816    528   ffffffff 00000000 S /init
root      2     0     0      0     ffffffff 00000000 S kthreadd
root      3     2     0      0     ffffffff 00000000 S ksoftirqd/0
root      5     2     0      0     ffffffff 00000000 S kworker/0:0H
root      7     2     0      0     ffffffff 00000000 S migration/0
root      8     2     0      0     ffffffff 00000000 S rcu_preempt
root      9     2     0      0     ffffffff 00000000 S rcu_bh
root      10    2     0      0     ffffffff 00000000 S rcu_sched
root      11    2     0      0     ffffffff 00000000 S watchdog/0
root      12    2     0      0     ffffffff 00000000 S watchdog/1
root      13    2     0      0     ffffffff 00000000 S migration/1
root      14    2     0      0     ffffffff 00000000 S ksoftirqd/1
root      16    2     0      0     ffffffff 00000000 S kworker/1:0H
root      17    2     0      0     ffffffff 00000000 S watchdog/2
root      18    2     0      0     ffffffff 00000000 S migration/2
root      19    2     0      0     ffffffff 00000000 S ksoftirqd/2
root      21    2     0      0     ffffffff 00000000 S kworker/2:0H
root      22    2     0      0     ffffffff 00000000 S watchdog/3
root      23    2     0      0     ffffffff 00000000 S migration/3
root      24    2     0      0     ffffffff 00000000 S ksoftirqd/3
root      25    2     0      0     ffffffff 00000000 S kworker/3:0
root      26    2     0      0     ffffffff 00000000 S kworker/3:0H
root      27    2     0      0     ffffffff 00000000 S khelper
root      28    2     0      0     ffffffff 00000000 S kdevtmpfs
root      29    2     0      0     ffffffff 00000000 S netns
root      30    2     0      0     ffffffff 00000000 S kworker/0:1
root      31    2     0      0     ffffffff 00000000 S kworker/3:1
root      32    2     0      0     ffffffff 00000000 S kworker/2:1
root      33    2     0      0     ffffffff 00000000 S kworker/1:1
root      34    2     0      0     ffffffff 00000000 S kconsole
root      35    2     0      0     ffffffff 00000000 S writeback
root      36    2     0      0     ffffffff 00000000 S bioset
root      37    2     0      0     ffffffff 00000000 S crypto
root      38    2     0      0     ffffffff 00000000 S kworker/u9:0
root      39    2     0      0     ffffffff 00000000 S kblockd
root      40    2     0      0     ffffffff 00000000 S khubd
root      68    2     0      0     ffffffff 00000000 S vmalloc
root      69    2     0      0     ffffffff 00000000 S cfg80211
root      70    2     0      0     ffffffff 00000000 S irq/160-rk805
root      71    2     0      0     ffffffff 00000000 S rk816_rtc
root      72    2     0      0     ffffffff 00000000 S irq/65-rga
root      73    2     0      0     ffffffff 00000000 S fb-vsync
root      74    2     0      0     ffffffff 00000000 S rk-fb
root      75    2     0      0     ffffffff 00000000 S cfinteractive
root      76    2     0      0     ffffffff 00000000 S rpciod
root      92    2     0      0     ffffffff 00000000 S khungtaskd
root      93    2     0      0     ffffffff 00000000 S kswapd0
root      94    2     0      0     ffffffff 00000000 S ksmd
root      95    2     0      0     ffffffff 00000000 S fsnotify_mark
root      96    2     0      0     ffffffff 00000000 S nfsiod
root      97    2     0      0     ffffffff 00000000 S cifsiod
root      118   2     0      0     ffffffff 00000000 S irq/63-20070000
root      119   2     0      0     ffffffff 00000000 S dwc_otg
root      120   2     0      0     ffffffff 00000000 S uether
root      121   2     0      0     ffffffff 00000000 S kpsmoused
root      122   2     0      0     ffffffff 00000000 S rk816_pwrkey
root      123   2     0      0     ffffffff 00000000 S irq/90-tsadc
root      124   2     0      0     ffffffff 00000000 S rockchip_tsadc
root      125   2     0      0     ffffffff 00000000 S dm_bufio_cache
root      126   2     0      0     ffffffff 00000000 S dw-mci-card
root      127   2     0      0     ffffffff 00000000 S dw-mci-card
root      128   2     0      0     ffffffff 00000000 S mmcqd/0
root      129   2     0      0     ffffffff 00000000 S mmcqd/0rpmb
root      130   2     0      0     ffffffff 00000000 S dw-mci-card
root      131   2     0      0     ffffffff 00000000 S binder
root      134   2     0      0     ffffffff 00000000 S krfcommd
root      136   2     0      0     ffffffff 00000000 S ddrfreqd
root      137   2     0      0     ffffffff 00000000 S dvfs
root      138   2     0      0     ffffffff 00000000 S kworker/0:1H
root      139   2     0      0     ffffffff 00000000 S deferwq
root      141   2     0      0     ffffffff 00000000 S f_mtp
root      142   2     0      0     ffffffff 00000000 S file-storage
root      143   2     0      0     ffffffff 00000000 S multi_leds0
root      144   2     0      0     ffffffff 00000000 S multi_leds1
root      145   1     756    424   ffffffff 00000000 S /sbin/ueventd
root      146   2     0      0     ffffffff 00000000 S wl_event_handle
root      147   2     0      0     ffffffff 00000000 S wl_escan_handle
root      148   2     0      0     ffffffff 00000000 S dhd_watchdog_th
root      149   2     0      0     ffffffff 00000000 S dhd_dpc
root      150   2     0      0     ffffffff 00000000 S dhd_rxf
root      154   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p14
root      155   2     0      0     ffffffff 00000000 S ext4-rsv-conver
root      159   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p10
root      160   2     0      0     ffffffff 00000000 S ext4-rsv-conver
root      164   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p12
root      165   2     0      0     ffffffff 00000000 S ext4-rsv-conver
root      169   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p11
root      170   2     0      0     ffffffff 00000000 S ext4-rsv-conver
root      175   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p15
root      176   2     0      0     ffffffff 00000000 S ext4-rsv-conver
root      177   2     0      0     ffffffff 00000000 S irq/43-20020000
root      178   2     0      0     ffffffff 00000000 S irq/41-20020000
root      179   2     0      0     ffffffff 00000000 S irq/39-20030000
logd      181   1     12228  5828  ffffffff 00000000 S /system/bin/logd
root      186   2     0      0     ffffffff 00000000 S kauditd
root      189   1     8024   956   ffffffff 00000000 S magiskd
root      194   189   1032   532   ffffffff 00000000 S /system/bin/logcat
root      196   1     1592   172   ffffffff 00000000 S /sbin/healthd
root      197   1     2376   1016  ffffffff 00000000 S /system/bin/lmkd
system    198   1     1244   556   ffffffff 00000000 S /system/bin/servicemanager
root      199   1     6424   916   ffffffff 00000000 S /system/bin/displayd
root      200   1     7724   2040  ffffffff 00000000 S /system/bin/vold
system    201   1     45152  4696  ffffffff 00000000 S /system/bin/surfaceflinger
shell     206   1     1116   520   c03344bc b6f27a14 S /system/bin/sh
root      207   1     11632  1192  ffffffff 00000000 S /system/bin/netd
root      208   1     1804   552   ffffffff 00000000 S /system/bin/debuggerd
root      209   1     6172   1520  ffffffff 00000000 S /system/bin/rild
install   210   1     1160   376   ffffffff 00000000 S /system/bin/installd
keystore  211   1     4324   1660  ffffffff 00000000 S /system/bin/keystore
root      216   1     815484 44600 ffffffff 00000000 S zygote
system    217   1     62428  10736 ffffffff 00000000 S /system/bin/mediaserver
media_rw  220   1     3576   336   ffffffff 00000000 S /system/bin/sdcard
shell     221   1     7716   212   ffffffff 00000000 S /sbin/adbd
root      356   2     0      0     ffffffff 00000000 S kworker/0:2
system    508   216   905608 67468 ffffffff 00000000 S system_server
u0_a1     663   216   563752 27416 ffffffff 00000000 S android.process.media
root      676   2     0      0     ffffffff 00000000 S kworker/2:2
u0_a2     698   216   561684 23256 ffffffff 00000000 S com.android.externalstorage
wifi      723   1     4484   2612  ffffffff 00000000 S /system/bin/wpa_supplicant
u0_a9     724   216   964204 127628 ffffffff 00000000 S com.phicomm.speaker.device
system    743   216   578456 34432 ffffffff 00000000 S com.phicomm.speaker.systemtool
system    760   216   576308 35500 ffffffff 00000000 S com.phicomm.speaker.player
u0_a6     785   216   562496 30940 ffffffff 00000000 S com.phicomm.speaker.launcher
u0_a9     907   216   832472 39952 ffffffff 00000000 S com.phicomm.speaker.device:remote
u0_a10    939   216   596308 30780 ffffffff 00000000 S com.picapico.audioshare
dhcp      962   1     1108   580   ffffffff 00000000 S /system/bin/dhcpcd
system    974   216   564020 24156 ffffffff 00000000 S com.phicomm.speaker.airskill
u0_a7     1011  216   573704 34988 ffffffff 00000000 S com.topjohnwu.magisk
system    1044  216   568052 30776 ffffffff 00000000 S com.phicomm.speaker.player:NetPlayer
radio     1073  216   561144 25676 ffffffff 00000000 S com.android.phone
system    1099  216   571048 32728 ffffffff 00000000 S com.phicomm.speaker.player:DlnaPlayer
u0_a7     1122  1011  4724   1516  ffffffff 00000000 S su
bluetooth 1124  216   604960 35660 ffffffff 00000000 S com.android.bluetooth
system    1141  216   571612 27404 ffffffff 00000000 S com.phicomm.speaker.netctl
root      1159  189   1180   604   ffffffff 00000000 S /system/bin/sh
system    1211  216   569332 33100 ffffffff 00000000 S com.phicomm.speaker.player:AirPlayer
system    1402  216   569008 33580 ffffffff 00000000 S com.phicomm.speaker.systemtool:remote
root      1583  2     0      0     ffffffff 00000000 S kworker/1:0
root      5223  2     0      0     ffffffff 00000000 S kworker/u9:1
root      5237  2     0      0     ffffffff 00000000 S kworker/u8:2
root      7940  2     0      0     ffffffff 00000000 S kworker/u8:0
shell     8177  221   2424   708   00000000 b6e9ba14 R ps


这是重启后连上蓝牙的进程，此时语音正常。
C:\Users\admin>adb shell ps
USER     PID   PPID  VSIZE  RSS     WCHAN    PC        NAME
root      1     0     816    524   ffffffff 00000000 S /init
root      2     0     0      0     ffffffff 00000000 S kthreadd
root      3     2     0      0     ffffffff 00000000 S ksoftirqd/0
root      4     2     0      0     ffffffff 00000000 S kworker/0:0
root      5     2     0      0     ffffffff 00000000 S kworker/0:0H
root      6     2     0      0     ffffffff 00000000 S kworker/u8:0
root      7     2     0      0     ffffffff 00000000 S migration/0
root      8     2     0      0     ffffffff 00000000 S rcu_preempt
root      9     2     0      0     ffffffff 00000000 S rcu_bh
root      10    2     0      0     ffffffff 00000000 S rcu_sched
root      11    2     0      0     ffffffff 00000000 S watchdog/0
root      12    2     0      0     ffffffff 00000000 S watchdog/1
root      13    2     0      0     ffffffff 00000000 S migration/1
root      14    2     0      0     ffffffff 00000000 S ksoftirqd/1
root      15    2     0      0     ffffffff 00000000 S kworker/1:0
root      16    2     0      0     ffffffff 00000000 S kworker/1:0H
root      17    2     0      0     ffffffff 00000000 S watchdog/2
root      18    2     0      0     ffffffff 00000000 S migration/2
root      19    2     0      0     ffffffff 00000000 S ksoftirqd/2
root      20    2     0      0     ffffffff 00000000 S kworker/2:0
root      21    2     0      0     ffffffff 00000000 S kworker/2:0H
root      22    2     0      0     ffffffff 00000000 S watchdog/3
root      23    2     0      0     ffffffff 00000000 S migration/3
root      24    2     0      0     ffffffff 00000000 S ksoftirqd/3
root      25    2     0      0     ffffffff 00000000 S kworker/3:0
root      26    2     0      0     ffffffff 00000000 S kworker/3:0H
root      27    2     0      0     ffffffff 00000000 S khelper
root      28    2     0      0     ffffffff 00000000 S kdevtmpfs
root      29    2     0      0     ffffffff 00000000 S netns
root      30    2     0      0     ffffffff 00000000 S kworker/0:1
root      31    2     0      0     ffffffff 00000000 S kworker/2:1
root      32    2     0      0     ffffffff 00000000 S kworker/3:1
root      33    2     0      0     ffffffff 00000000 S kworker/1:1
root      34    2     0      0     ffffffff 00000000 S kconsole
root      35    2     0      0     ffffffff 00000000 S writeback
root      36    2     0      0     ffffffff 00000000 S bioset
root      37    2     0      0     ffffffff 00000000 S crypto
root      38    2     0      0     ffffffff 00000000 S kworker/u9:0
root      39    2     0      0     ffffffff 00000000 S kblockd
root      40    2     0      0     ffffffff 00000000 S khubd
root      41    2     0      0     ffffffff 00000000 S kworker/u8:1
root      68    2     0      0     ffffffff 00000000 S vmalloc
root      69    2     0      0     ffffffff 00000000 S cfg80211
root      70    2     0      0     ffffffff 00000000 S irq/160-rk805
root      71    2     0      0     ffffffff 00000000 S rk816_rtc
root      72    2     0      0     ffffffff 00000000 S irq/65-rga
root      73    2     0      0     ffffffff 00000000 S fb-vsync
root      74    2     0      0     ffffffff 00000000 S rk-fb
root      75    2     0      0     ffffffff 00000000 S cfinteractive
root      76    2     0      0     ffffffff 00000000 S rpciod
root      92    2     0      0     ffffffff 00000000 S khungtaskd
root      93    2     0      0     ffffffff 00000000 S kswapd0
root      94    2     0      0     ffffffff 00000000 S ksmd
root      95    2     0      0     ffffffff 00000000 S fsnotify_mark
root      96    2     0      0     ffffffff 00000000 S nfsiod
root      97    2     0      0     ffffffff 00000000 S cifsiod
root      118   2     0      0     ffffffff 00000000 S irq/63-20070000
root      119   2     0      0     ffffffff 00000000 S dwc_otg
root      120   2     0      0     ffffffff 00000000 S uether
root      121   2     0      0     ffffffff 00000000 S kpsmoused
root      122   2     0      0     ffffffff 00000000 S rk816_pwrkey
root      123   2     0      0     ffffffff 00000000 S irq/90-tsadc
root      124   2     0      0     ffffffff 00000000 S rockchip_tsadc
root      125   2     0      0     ffffffff 00000000 S dm_bufio_cache
root      126   2     0      0     ffffffff 00000000 S dw-mci-card
root      127   2     0      0     ffffffff 00000000 S dw-mci-card
root      128   2     0      0     ffffffff 00000000 S mmcqd/0
root      129   2     0      0     ffffffff 00000000 S mmcqd/0rpmb
root      130   2     0      0     ffffffff 00000000 S dw-mci-card
root      131   2     0      0     ffffffff 00000000 S binder
root      132   2     0      0     ffffffff 00000000 S kworker/u8:2
root      133   2     0      0     ffffffff 00000000 S kworker/u8:3
root      134   2     0      0     ffffffff 00000000 S krfcommd
root      136   2     0      0     ffffffff 00000000 S ddrfreqd
root      137   2     0      0     ffffffff 00000000 S dvfs
root      138   2     0      0     ffffffff 00000000 S kworker/0:1H
root      139   2     0      0     ffffffff 00000000 S deferwq
root      141   2     0      0     ffffffff 00000000 S f_mtp
root      142   2     0      0     ffffffff 00000000 S file-storage
root      143   2     0      0     ffffffff 00000000 S multi_leds0
root      144   2     0      0     ffffffff 00000000 S multi_leds1
root      145   1     756    424   ffffffff 00000000 S /sbin/ueventd
root      146   2     0      0     ffffffff 00000000 S wl_event_handle
root      147   2     0      0     ffffffff 00000000 S wl_escan_handle
root      148   2     0      0     ffffffff 00000000 S dhd_watchdog_th
root      149   2     0      0     ffffffff 00000000 S dhd_dpc
root      150   2     0      0     ffffffff 00000000 S dhd_rxf
root      153   2     0      0     ffffffff 00000000 S kworker/u9:1
root      154   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p14
root      155   2     0      0     ffffffff 00000000 S ext4-rsv-conver
root      159   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p10
root      160   2     0      0     ffffffff 00000000 S ext4-rsv-conver
root      164   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p12
root      165   2     0      0     ffffffff 00000000 S ext4-rsv-conver
root      169   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p11
root      170   2     0      0     ffffffff 00000000 S ext4-rsv-conver
root      175   2     0      0     ffffffff 00000000 S jbd2/mmcblk0p15
root      176   2     0      0     ffffffff 00000000 S ext4-rsv-conver
root      177   2     0      0     ffffffff 00000000 S irq/43-20020000
root      178   2     0      0     ffffffff 00000000 S irq/41-20020000
root      179   2     0      0     ffffffff 00000000 S irq/39-20030000
logd      181   1     8356   1872  ffffffff 00000000 S /system/bin/logd
root      186   2     0      0     ffffffff 00000000 S kauditd
root      189   1     8024   960   ffffffff 00000000 S magiskd
root      194   189   1032   532   ffffffff 00000000 S /system/bin/logcat
root      196   1     1592   172   ffffffff 00000000 S /sbin/healthd
root      197   1     2376   1016  ffffffff 00000000 S /system/bin/lmkd
system    198   1     1244   556   ffffffff 00000000 S /system/bin/servicemanager
root      199   1     6424   692   ffffffff 00000000 S /system/bin/displayd
root      200   1     7724   2040  ffffffff 00000000 S /system/bin/vold
system    201   1     46164  4656  ffffffff 00000000 S /system/bin/surfaceflinger
shell     206   1     1116   520   c03344bc b6ec5a14 S /system/bin/sh
root      207   1     11612  1296  ffffffff 00000000 S /system/bin/netd
root      208   1     1860   1048  ffffffff 00000000 S /system/bin/debuggerd
root      209   1     6172   1520  ffffffff 00000000 S /system/bin/rild
install   210   1     1160   376   ffffffff 00000000 S /system/bin/installd
keystore  211   1     4324   1660  ffffffff 00000000 S /system/bin/keystore
root      216   1     815484 46648 ffffffff 00000000 S zygote
system    217   1     62428  10684 ffffffff 00000000 S /system/bin/mediaserver
media_rw  220   1     3576   336   ffffffff 00000000 S /system/bin/sdcard
shell     221   1     7716   212   ffffffff 00000000 S /sbin/adbd
root      360   2     0      0     ffffffff 00000000 S kworker/2:2
system    513   216   904588 63704 ffffffff 00000000 S system_server
root      552   2     0      0     ffffffff 00000000 S kworker/u9:2
root      665   2     0      0     ffffffff 00000000 S kworker/0:2
u0_a1     666   216   563752 28180 ffffffff 00000000 S android.process.media
u0_a2     701   216   561684 24236 ffffffff 00000000 S com.android.externalstorage
wifi      723   1     4512   2628  ffffffff 00000000 S /system/bin/wpa_supplicant
u0_a9     726   216   962576 123792 ffffffff 00000000 S com.phicomm.speaker.device
system    744   216   579468 34072 ffffffff 00000000 S com.phicomm.speaker.systemtool
system    761   216   571180 35548 ffffffff 00000000 S com.phicomm.speaker.player
u0_a6     780   216   564568 31664 ffffffff 00000000 S com.phicomm.speaker.launcher
u0_a9     911   216   836800 40516 ffffffff 00000000 S com.phicomm.speaker.device:remote
u0_a10    941   216   596336 30244 ffffffff 00000000 S com.picapico.audioshare
system    973   216   565088 25516 ffffffff 00000000 S com.phicomm.speaker.airskill
u0_a7     1004  216   573704 35696 ffffffff 00000000 S com.topjohnwu.magisk
system    1024  216   568052 31544 ffffffff 00000000 S com.phicomm.speaker.player:NetPlayer
u0_a7     1054  1004  4724   1516  ffffffff 00000000 S su
system    1056  216   572680 28140 ffffffff 00000000 S com.phicomm.speaker.netctl
system    1077  216   572080 34372 ffffffff 00000000 S com.phicomm.speaker.player:DlnaPlayer
root      1078  189   1180   604   ffffffff 00000000 S /system/bin/sh
bluetooth 1143  216   602832 35144 ffffffff 00000000 S com.android.bluetooth
system    1185  216   570324 34068 ffffffff 00000000 S com.phicomm.speaker.player:AirPlayer
root      1362  2     0      0     ffffffff 00000000 S kworker/u8:4
radio     1394  216   561144 26312 ffffffff 00000000 S com.android.phone
root      1465  2     0      0     ffffffff 00000000 S kworker/3:2
dhcp      1504  1     1108   580   ffffffff 00000000 S /system/bin/dhcpcd
root      1548  2     0      0     ffffffff 00000000 S kworker/u8:5
system    1554  216   568776 33840 ffffffff 00000000 S com.phicomm.speaker.systemtool:remote
shell     1595  221   2424   708   00000000 b6eafa14 R ps

C:\Users\admin>

**Comment by xdm2211** [comment]
> [最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)加入了在线播放功能的关闭按钮，关闭后重启生效

1.7.9关掉了在线播放音乐还是不行。

**Comment by HeHang0** [comment]
> > [最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)加入了在线播放功能的关闭按钮，关闭后重启生效
> 
> 1.7.9关掉了在线播放音乐还是不行。

看上去进程信息基本上都是一致的，只能发logcat来分析了。

**Comment by xdm2211** [comment]
> > > [最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)加入了在线播放功能的关闭按钮，关闭后重启生效
> > 
> > 
> > 1.7.9关掉了在线播放音乐还是不行。
> 
> 看上去进程信息基本上都是一致的，只能发logcat来分析了。

这个就有点不会搞了啊。能不能麻烦编译一个不关闭其它进程的版本 发我试试啊？因为我多次测试 只要安装了后蓝牙模式连续播放超过12个小时以上就唤不醒了。但是我还原出厂不安装这个app就可以一直正常。。

**Comment by HeHang0** [comment]
> > > > [最新版本v1.7.9](https://github.com/HeHang0/AudioShare/releases/latest)加入了在线播放功能的关闭按钮，关闭后重启生效
> > > 
> > > 
> > > 1.7.9关掉了在线播放音乐还是不行。
> > 
> > 
> > 看上去进程信息基本上都是一致的，只能发logcat来分析了。
> 
> 这个就有点不会搞了啊。能不能麻烦编译一个不关闭其它进程的版本 发我试试啊？因为我多次测试 只要安装了后蓝牙模式连续播放超过12个小时以上就唤不醒了。但是我还原出厂不安装这个app就可以一直正常。。

app本身没有关闭其他进程的功能，无法唤醒的问题我这边也出现了，目前没看出来有直接关系导致无法唤醒。
使用下面的命令可以导出日志到桌面:
`adb logcat -v time > C:\Users\用户名\Desktop\log.txt`
